### ISSUE TITLE
Pre element results in error

### ISSUE THREAD

**Issue by RifRaf44** [nicojs/html2commonmark#14]
Converting a 'pre' element results in an error. For example: `"<pre>Foobar</pre>"`
In the following piece, the variable code is null, which results in checking an undefined property.

```
if (!info.length && (code.length > 2 && !Util_1.default.isSpace(code[0])) &&
                                    !(Util_1.default.isSpace(code[code.length - 1]) && Util_1.default.isSpace(code[code.length - 2])) &&
                                    !(!node.prev && node.parent && node.parent.type == 'Item'))

```

**Comment by nicojs** [comment]
The result in error is fixed. I created issue #17 for the conversion of lonely `pre` tags
